
name: ordinal-mil-nnets
channels:
  - defaults
dependencies:
  - keras=2.6.0
  - pandas=1.4.3
  - pip=21.2.4
  - python=3.8.5
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - wheel=0.37.1
  - pip:
    - cifar10==1.0.0
    - "--editable=git+https://github.com/ck37/coral-ordinal/"
    - coral-ordinal==0.1.9.dev0
    - h5py==2.10.0
    - image==1.5.33
    - keras-preprocessing==1.1.2
    - numpy==1.19.5
    - pillow>=9.2.0
    - tensorboard==2.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - tensorflow-probability==0.17.0
    - tensorflow-hub==0.12.0
    - tensorflow-text==2.4.1
    - nltk==3.8
    